const CONSTANTS_TEXT = {
    login: "Por favor, ingrese su número de DUI y contraseña para continuar.",
    register_success: "Registro exitoso. Ahora puede iniciar sesión con su número de DUI y contraseña.",
    invalid_DUI: "Ingresa un DUI válido (xxxxxxxx-x)",
    invalid_credentials: "Credenciales inválidas. Por favor, verifique e inténtelo nuevamente.",
    incomplete_data: "Faltan datos por ingresar. Verifique la información e inténtelo nuevamente.",
    invalid_email: "Ingresa un email válido",
    password_mismatch: "La contraseña y su confirmación no coinciden. Por favor, verifique e inténtelo nuevamente.",
    user_exists: "Ya existe un usuario registrado con este número de DUI.",
    incomplete_NUI_NIE: "NUI/NIE es requerido para registrar a su niño/a.",
    invalid_NUI_NIE: "NUI/NIE debe tener el formato correcto (xxxxxxxx-x).",
    user_not_found: "Usuario no encontrado. Por favor, verifique el número de DUI e inténtelo nuevamente.",
    child_not_found: "No se encontró un niño/a asociado a este número de NUI/NIE. Por favor, verifique el número e inténtelo nuevamente.",
    child_exists: "Ya existe un niño/a registrado con este número de NUI/NIE.",
    child_registered: "Niño/a registrado exitosamente.",
    child_deleted: "Niño/a eliminado exitosamente.",
    basic_data_added: "Dato básico del niño/a agregado con éxito.",
    allergies_added: "Alergia del niño/a agregada con éxito.",
    conditions_added: "Condición del niño/a agregada con éxito.",
    medications_added: "Medicación del niño/a agregada con éxito.",
    professional_preferred_added: "Profesional preferido del niño/a agregado con éxito.",
    item_updated: "Dato actualizado con éxito.",
    item_deleted: "Dato eliminado con éxito.",
    error_item_deleted: "No se pudo eliminar el dato.",
    error_item_updated: "No se pudo actualizar el dato.",
    user_deleted: "Usuario eliminado exitosamente.",
    login_success: "Inicio de sesión exitoso.",
    connection_success: "conexion exitosa :)",
    server_listening: "Server listening on port: ",
    email_missing: "Debe ingresar su correo electrónico.",
    email_not_found: "No se encontró ningún usuario registrado con este correo electrónico.",
    code_send: "El código de verificación ha sido enviado exitosamente a su correo electrónico. Por favor, revise su bandeja de entrada y utilice el código para continuar con el proceso de cambio de contraseña.",
    changePassword_request_not_found: "No se encontró una solicitud de cambio de contraseña para este correo electrónico. Por favor, verifique la información e inténtelo nuevamente.",
    invalid_code: "El código de verificación es inválido. Por favor, verifique el código e inténtelo nuevamente.",
    password_changed: "Contraseña actualizada exitosamente. Ahora puede iniciar sesión con su nueva contraseña.",
    exits_request: "Ya existe una solicitud de cambio de contraseña para este correo electrónico. Por favor, revise su bandeja de entrada y utilice el código enviado anteriormente para continuar con el proceso de cambio de contraseña."
}

export default CONSTANTS_TEXT